name: Contract Testing

on:
  push:
    branches:
      - main

jobs:
  contract-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Contract Testing
        run: mvn verify -B -Dmaven.resolver.transport=wagon

      - name: Upload Surefire Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
